### ISSUE TITLE
suspicious similar fluorescence from different identified neurons at different locations

### ISSUE THREAD

**Issue by XiaoqianSun0104** [flatironinstitute/CaImAn#1063]
Hi,

When checking the results using nb_view_components(), I found florescence traces from several identified neurons look similar to each other which I felt concerned about.  Any thoughts on what went wrong and how to improve? Or it's actually OK? Thank you.

<img width="1166" alt="1" src="https://user-images.githubusercontent.com/31903092/231923669-39d9e6cb-5351-457d-a59a-75d22c6f8d32.png">
<img width="1160" alt="2" src="https://user-images.githubusercontent.com/31903092/231923670-c590537d-baf8-4ff6-82d8-53c7066b027b.png">
<img width="1175" alt="3" src="https://user-images.githubusercontent.com/31903092/231923671-1be45ec6-8487-4189-aed7-0ab7a12b65f5.png">
<img width="1163" alt="4" src="https://user-images.githubusercontent.com/31903092/231923681-216babf9-1eaa-43bd-9cad-14c53c9bf4d0.png">

**Comment by EricThomson** [comment]
It doesn't look like artifact to me. I wouldn't assume something went wrong esp with neurons that far apart. And without more knowledge of brain region I definitely wouldn't want to speculate much: are they all visual neurons being driven by the same visual stimulus, for instance? Could they be being driven by the same presynaptic neuron/circuit like a neuromodulator? Is the animal anesthetized or sleeping (which often results in synchronous activity)? But just looking at these signals they look reasonable.

**Comment by EricThomson** [comment]
Also, as I think about it, what I do with my data (especially with components that are far apart) is use the eyeball test. Are the traces extracted accurately reflecting what you see in the segmented components pulled out? This is pretty easy to see by eye when you scroll through the movie and look at the traces. Doe the traces look like a reasonable estimate of the activity in the movie? If not, then that typically suggests I need to increase my SNR threshold in my evaluation metrics because I'm getting false positives. If so, then you are usually good to go.

**Comment by EricThomson** [comment]
Closing because issue seems resolved. If this was a mistake, please reopen @XiaoqianSun0104
