### ISSUE TITLE
Parametrization setup with .TIF

### ISSUE THREAD

**Issue by andyrdar** [flatironinstitute/CaImAn#1114]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: Dual-Core Intel Core i7 and 16GB
 3. Python Version (e.g. 3.9): 3.10.11
 4. Caiman version (e.g. 1.9.12): 1.9.14
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda
 7. Details: 
The code is working fine, but I am having some issues with parameter settings. I was only given the frame rate and decay time for the data I'm currently using, .TIF files dimension 154 × 510. Since I don't know the amount of overlap between patches, # of components per patch or any of the other values for parametrization of source extraction, the identified components end up looking weird. Any idea how to proceed?

**Comment by EricThomson** [comment]
@andyrdar I assume you are working through `demo_pipeline.ipynb` which is for CNMF. 

Generally, these parameters will be dataset-dependent so it's really about inspecting your data (either movies or summary images like max projections or correlation images).  I am currently working on revamping the CNMF notebook so that these things are explained in more detail.  Since you are asking about num components per patch, I assume you already have successfully motion corrected your movie.  

As I said, these parameters you use will depend on the details of your data. I recommend setting `rf` (which is half the patch width) to about 4x the diameter of the neurons in your data set. You need to estimate neuron diameter by checking out your data, which you can inspect from either a max projection or a correlation image (or some other summary template, or just by inspecting your movies). 

For instance here's how you would get a correlation image (which shows how correlated each pixel in the image is, on average, with its neighbors):

```
correlation_image = cm.local_correlations(m_els, swap_dim=False)
correlation_image[np.isnan(correlation_image)] = 0 # get rid of NaNs, if they exist
```

Where `m_els` is the loaded motion corrected file from the demo notebook (the line after the motion correction step). 

And plot with _something_ like the following (adjusting vmin and vmax depending on your data):
```
plt.imshow(correlation_image, cmap='gray') #adjust vmin, vmax as needed
plt.set_title('Correlation Image', fontsize=15);
```
To set K, which is the number of neurons per patch, you would pick an upper bound based on inspection of your data. How many neurons do you think you have in each patch of width `rf*2`? For overlap, I usually just pick an integer that is close to `rf//2` (and that's `cnmf_stride`, which is a poor choice of terms on our part admittedly). 

But also note all these things are _parameters_ and you can do a search over parameter space. You don't have to just pick one and hope you got it right. You can pick a few values of rf/K (and other params) and see which yields the best results. Usually things aren't super sensitive to `rf`, but they can be _very_ sensitive to K. I'd try a few different values of K that seem roughly reasonable to you based on inspection of the data, and see how it seems.

Also, I strongly recommend checking out this part of the docs on what parameters are most important:
https://caiman.readthedocs.io/en/master/Getting_Started.html#parameters

And subsequent sections on component evaluation and interpretation.

**Comment by andyrdar** [comment]
That makes more sense! Thank you Eric.

**Comment by EricThomson** [comment]
Thanks for opening your first issue with us! Let me know if you have more questions. If you consider the issue settled, you can click on the 'Close issue` button at the bottom of the page.

**Comment by EricThomson** [comment]
Closing as it seems this is resolved
