### ISSUE TITLE
Our bokeh calls rely on flags removed in bokeh 3.x

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#1127]
Bokeh 3.x removed plot_width and plot_height:
https://github.com/bokeh/bokeh/wiki/Migration-Guides#changes-310

They suggest using `width` and `height` instead. We should probably review other bokeh changes now that unpinning holoviews pulls several related packages forward into the modern age, graphics stack wise, but we at least need to fix this.

This is a release blocker before the next version.

**Comment by EricThomson** [comment]
It is almost ready: I worked through all the demo notebooks, and everything is working except for `nb_view_components_3d()` in `demo_caiman_cnmf_3D.ipynb`. This relies on `caiman.utils.visualization.nb_view_patches3d()` which is a complex function that I've never really worked through or understood fully.

The main problem (aside from `plot_height`) is that bokeh seems to have changed how they set the origin of the image. It was easy to fix (setting `plot.image(y=0)` instead of `y=num_rows`.

For instance, in `nb_view_components()`, I got things to render properly by changing:

`plot1.image(image=[image_neurons[::-1, :]], x=0, y=image_neurons.shape[0], dw=d2, dh=d1, palette=grayp)
`
to: 

`plot1.image(image=[image_neurons[::-1, :]], x=0, y=0, dw=d2, dh=d1, palette=grayp)
`

After fiddling for a while, I'm not sure how to do this in the 3d version but I may just need a set of fresh eyes on it. I know @j-friedrich wrote a lot of that code maybe it will be obvious to you?

One other thing @pgunn, for `demo_online_cnmfE.ipynb` the avi file wouldn't load for me, I got an error: `
ImportError: This reader requires PyAV, MoviePy, or ImageIO.`. I already have imageio installed. I tried installing pyav, and still got the same error. I know you tweaked the file i/o a bit, so not sure what is going on there. For that nb, I just imported a tiff instead to get things working.

**Comment by j-friedrich** [comment]
I'll take a look at `nb_view_patches3d()` next week

**Comment by j-friedrich** [comment]
`nb_view_patches3d()` is working now with bokeh 3 (but breaking backward compatibility with bokeh<3)

**Comment by EricThomson** [comment]
The initial PR for fixing the bokeh visualizations (#1129 ) fixed the problems with the 2d plotters, but `nb_view_components_3d()` has some residual problems. E.g., when plotting layered (no max projection) the image and patches don't seem properly matched : one of them seems flipped on the horizontal axis (note this isn't just a layer artifact -- this is the best layer for that neuron).:

![bokeh_layered_view](https://github.com/flatironinstitute/CaImAn/assets/6643322/9414d8bf-145e-43ac-a795-7a858568f8f1)

Then with the max projection view (with `axis=2`) things are wonky: the panels are shifted, I'm not sure exactly what has gone wrong:

![bokeh_max_axis2](https://github.com/flatironinstitute/CaImAn/assets/6643322/22f2f7ff-b189-4a9c-a6b5-ee50e02fed1d)

I think we shouldn't let this block release of 1.10, so we should push the PR into dev. My plan, until this is fixed is to put a note in the notebooks where this is used, and issue a logger warning when it is invoked. 

@j-friedrich maybe we can work on this at the workshop.

**Comment by EricThomson** [comment]
Revisiting this: things are more messy than I thought as I found out when I tried to run things in colab, and issues seem to keep cropping up with people. Here's a summary of what I've found, and what seems to be a viable path forward so this doesn't have to block the next caiman release.

There is a coupling between bokeh, holoviews, and panel. They all tend to migrate together. Bokeh seems to be the leading package that the others follow. We have run into problems with this before:
https://github.com/flatironinstitute/CaImAn/issues/760

At that issue, there was some punk kid who wrote:

"I downgraded to holoviews 1.12.3, got an import error with hv.notebook_extension('bokeh') -- ImportError: `None of the backends could be imported`. This is a known incompatibility between holoviews 1.12 and Bokeh 2+ (holoviz/holoviews#4280). When I downgrade to Bokeh 1.4 and Holoviews 1.12, i**t seems things work: maybe something to keep an eye on, compatibility-wise, moving forward?**"

With the current problem we have Boken 3.0 killing our plotting tools (not sure why we didn't get deprecation warnings from Bokeh with this, that would have been super helpful. Maybe we did and didn't notice? I feel like I would have noticed but there is a chance I didn't!).

At any rate, this is clearly something we are just going to have to track moving forward if we keep using Bokeh because this is a known problem.

At any rate, I spent some time this afternoon researching the series of releases that lead to our problems:

**Bokeh** 2.4.3 to 3.0 (October 2022): https://docs.bokeh.org/en/latest/docs/releases.html#release-3-0-0
There is a migration guide, and this will take some work (that we started and tried to do quickly, but it will just take a bit of time to get it right) --  https://github.com/bokeh/bokeh/wiki/Migration-Guides

**Holoviews** updated from 1.15.4 to 1.16.0 (May 9, 2023), making sure they are compliant with Bokeh.
https://holoviews.org/releases.html#version-1-16-0

**Panel** follows with a fairly major release, from 0.14.4 to 1.0.0 on May 17 2023.

At any rate, these changes were major enough that it is a major shift for us to migrate. The above changes also explains why the colab branch I made works: it wasn't quite right. There, I pinned at:
```

bokeh<=2.4.2
holoviews<=1.15.2
panel<=0.14.4
```

I also pinned pandas at<=2.0.1 but I that shouldn't be necessary I'm not sure why I did that. 

We should be able to do the dev branch with the following. 

First, just keep our bokeh plotters the same. Second, roll back bokeh major release:

```
Bokeh<3.0
Holoviews<1.16
Panel<1.0
```

These three pins from the coupled trinity of trouble should get rid of the problem that led to #1120 (@pgunn could you please confirm?), and give us time to properly update our plotting functions to adhere to Bokeh 3.0 standards within a year of its release (which isn't that bad, really). 

While it's a pain to track these three libraries, the nice thing is that their release notes do reference each other (or at least Panels/Holoviews reference bokeh).

**Comment by EricThomson** [comment]
Fixed in most recent release 🎆
