### ISSUE TITLE
Demo Notebook for onACID

### ISSUE THREAD

**Issue by raymondwjang** [flatironinstitute/CaImAn#1411]
Hello,

just about to begin trying OnACID package out, but I cannot tell which demo corresponds to the onACID one based on the notebook names. 

Could somebody tell me what the difference between`demo_realtime_cnmfE.ipynb` and `demo_online_cnmfE.ipynb` is?

**Comment by pgunn** [comment]
Hello,
Both of them demonstrate online processing. demo_online_cnmfE is a simpler demo that you'll probably want to start with to learn the online flow, unless you have reason to do otherwise. demo_realtime additionally demonstrates the ring_cnn component, and shows you more options to process the data that you might consider; you might consider using its approaches after you're comfortable with demo_online_cnmfE.

Cheers,
Pat

**Comment by kushalkolar** [comment]
The demo notebooks give some overview, but if your usecase is to integrate it with realtime experiments I suggest looking at the caiman demos with improv: https://github.com/project-improv/improv

**Comment by raymondwjang** [comment]
That clarifies. Thank you, @pgunn and @kushalkolar !
