### ISSUE TITLE
Question about running source extraction for multiple trials

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#204]
Dear CaImAn developers,

I would like to ask for some advice on how to run CaImAn source extraction on experiments with very many, short trials (in our case 100s of trials, each approximately 10s long). I can think of two ways of how to deal with this:
1. Concatenate all trials and run source extraction once on the concatenated movie. 
2. Run source extraction for each trial's movie and then somehow merge the identified components. 
Do you have any advise what would be better? If it makes more sense to merge components from individual trials, how can this be done in practice?

Thanks for your help.

Best regards, Henry

**Comment by agiovann** [comment]
Dear @hluetck 

I suggest to group your files so that each tif file contains ~3000 frames. In caiman this is rather easy. Say that fls_grp is a list containing the path to 10 of your files. Then
import caiman as cm
movs = cm.load(fls_grp)
fls.save('group1.hdf5')

And so on for each file. Then  use the demo pipeline file and pass as input the list of the hdf5 files you generated. Please let me know if this solves your problem!

Cheers

**Comment by epnev** [comment]
@hluetck I'm closing this issue but feel free to re-open if you want to follow up on this.
