### ISSUE TITLE
Problems with installation using anaconda

### ISSUE THREAD

**Issue by MingkangLi** [flatironinstitute/CaImAn#418]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Windows

- **Describe the issue that you are experiencing**
When I activate caiman environment using "activate caiman"，anaconda prompt shuts down immediately. I have no time to see the errors in anaconda prompt.

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
The last time this happened it had to do with oddities with the conda package that links the MSVC++ CLI utils to your conda environment. Could you try the following?

`conda install -n caiman vs2017_win-64`

**Comment by pgunn** [comment]
@Zaikkp Hi, did you get the chance to try any of the above?

**Comment by vathalye** [comment]
Hi, 
I'm having the same issue as Zaikkp.  It appeared during caiman installation on two windows machines ( 1) Windows 7 with Python 3.7, 2) Windows 10 with Python 3.6.6), each of which had Microsoft Build Tools for Visual Studio 2017 installed.  (I will note that I did not have this issue when installing caiman in May 2018.)

Ultimately, I was able to finish the caiman installation on both computers, and demo_pipeline works properly, which performs caiman batch.  However, the OnAcid demo does not work, resulting in errors suggesting issues linking to tools in Visual Studio 2017.  I would greatly appreciate assistance in sorting out these installation-related errors.

--
Details, Step by step: 

First, when I activated the caiman environment, the anaconda prompt closes immediately.  I piped the output to a textfile, contents follow: 

C:\Users\Proxeddu>set "KERAS_BACKEND=theano" 

C:\Users\Proxeddu>SET DISTUTILS_USE_SDK=1 

C:\Users\Proxeddu>SET MSSdk=1 

C:\Users\Proxeddu>SET platform= 

C:\Users\Proxeddu>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Users\Proxeddu>IF /I [] == [amd64] set "platform=true" 

C:\Users\Proxeddu>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 

C:\Users\Proxeddu>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B" 

C:\Users\Proxeddu>if "" == "" (set "VSINSTALLDIR=" ) 

C:\Users\Proxeddu>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"  
 exit 1 
) 
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"

--
I tried using pgunn's recommendation by running: 
conda install -n caiman vs2017_win-64

But this alone didn't resolve this particular issue; I got the same error message listed above.  

Because the error message suggested that I was unable to properly link to Visual Studio Build Tools, I spent some time adjusting which components were installed by Visual Studio.  I can go into more detail about this, but long story short: By adjusting components installed by Visual Studio, I'm able to eventually get the caiman installation to finish.  

However, note that activating caiman then resulted in a long printout: 

C:\Users\Proxeddu>set "KERAS_BACKEND=theano" 

C:\Users\Proxeddu>SET DISTUTILS_USE_SDK=1 

C:\Users\Proxeddu>SET MSSdk=1 

C:\Users\Proxeddu>SET platform= 

C:\Users\Proxeddu>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Users\Proxeddu>IF /I [] == [amd64] set "platform=true" 

C:\Users\Proxeddu>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 

C:\Users\Proxeddu>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B" 

C:\Users\Proxeddu>if "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" == "" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\" ) 

C:\Users\Proxeddu>if "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"  
 exit 1 
) 

C:\Users\Proxeddu>echo "Found VS2014 at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" 
"Found VS2014 at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\"

C:\Users\Proxeddu>SET "VS_VERSION=14.0" 

C:\Users\Proxeddu>SET "VS_MAJOR=14" 

C:\Users\Proxeddu>SET "VS_YEAR=2015" 

C:\Users\Proxeddu>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out" 

C:\Users\Proxeddu>set "MSYS2_ENV_CONV_EXCL=CL" 

C:\Users\Proxeddu>set "PY_VCRUNTIME_REDIST=\vcruntime140.dll" 

C:\Users\Proxeddu>set "CFLAGS= -MD -GL -MD -GL" 

C:\Users\Proxeddu>set "CXXFLAGS= -MD -GL -MD -GL" 

C:\Users\Proxeddu>set "LDFLAGS_SHARED= -LTCG ucrt.lib -LTCG ucrt.lib" 

C:\Users\Proxeddu>IF /I [] == [win-64] (set "folder=x64" )  else (set "folder=x86" ) 

C:\Users\Proxeddu>for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\*1*" /B /O:N') do for %A in (%~I) do if "%A" == "8.1" set win=%A 

C:\Users\Proxeddu>for %A in (10) do if "%A" == "8.1" set win=%A 

C:\Users\Proxeddu>if "10" == "8.1" set win=10 

C:\Users\Proxeddu>for %A in (8.1) do if "%A" == "8.1" set win=%A 

C:\Users\Proxeddu>if "8.1" == "8.1" set win=8.1 

C:\Users\Proxeddu>for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\*1*" /B /O:N') do for %A in (%~I) do if "%A" == "10" set win=%A 

C:\Users\Proxeddu>for %A in (10) do if "%A" == "10" set win=%A 

C:\Users\Proxeddu>if "10" == "10" set win=10 

C:\Users\Proxeddu>for %A in (8.1) do if "%A" == "10" set win=%A 

C:\Users\Proxeddu>if "8.1" == "10" set win=8.1 

C:\Users\Proxeddu>setlocal enabledelayedexpansion 

C:\Users\Proxeddu>if "10" == "10" (
for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\10\bin\10*" /B /O:N') do for %A in (%~I) do set last=%A  
 set "sdk_bin_path=C:\Program Files (x86)\Windows Kits\10\bin\!last!\x86" 
)  else (set "sdk_bin_path=C:\Program Files (x86)\Windows Kits\8.1\bin\x86" ) 

C:\Users\Proxeddu>for %A in (10.0.14393.0) do set last=%A 

C:\Users\Proxeddu>set last=10.0.14393.0 

C:\Users\Proxeddu>for %A in (10.0.15063.0) do set last=%A 

C:\Users\Proxeddu>set last=10.0.15063.0 

C:\Users\Proxeddu>for %A in (10.0.16299.0) do set last=%A 

C:\Users\Proxeddu>set last=10.0.16299.0 

C:\Users\Proxeddu>for %A in (10.0.17134.0) do set last=%A 

C:\Users\Proxeddu>set last=10.0.17134.0 

C:\Users\Proxeddu>for %A in (10.0.17763.0) do set last=%A 

C:\Users\Proxeddu>set last=10.0.17763.0 

C:\Users\Proxeddu>endlocal   & set "PATH=C:\Anaconda3\envs\caiman;C:\Anaconda3\envs\caiman\Library\mingw-w64\bin;C:\Anaconda3\envs\caiman\Library\usr\bin;C:\Anaconda3\envs\caiman\Library\bin;C:\Anaconda3\envs\caiman\Scripts;C:\Anaconda3\envs\caiman\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\;C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\usr\bin;C:\Anaconda3\Library\bin;C:\Anaconda3\Scripts;C:\Anaconda3\bin;C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\usr\bin;C:\Anaconda3\Library\bin;C:\Anaconda3\Scripts;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Dell\Dell Data Protection\Drivers\TSS\bin\;C:\Program Files\MATLAB\MATLAB Runtime\v851\runtime\win64;C:\Python27\;C:\Program Files\MATLAB\R2017a\runtime\win64;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cuda\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\Proxeddu\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86" 

C:\Users\Proxeddu>SET "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"  

C:\Users\Proxeddu>CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\..\..\VC\vcvarsall.bat" amd64  

C:\Users\Proxeddu>SET DISTUTILS_USE_SDK=1 

C:\Users\Proxeddu>SET MSSdk=1 

C:\Users\Proxeddu>SET "VS_VERSION=15.0" 

C:\Users\Proxeddu>SET "VS_MAJOR=15" 

C:\Users\Proxeddu>SET "VS_YEAR=2017" 

C:\Users\Proxeddu>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out" 

C:\Users\Proxeddu>set "MSYS2_ENV_CONV_EXCL=CL" 

C:\Users\Proxeddu>set "PY_VCRUNTIME_REDIST=\\bin\\vcruntime140.dll" 

C:\Users\Proxeddu>set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" 

C:\Users\Proxeddu>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" ) 

C:\Users\Proxeddu>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" ) 

C:\Users\Proxeddu>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\" ) 

C:\Users\Proxeddu>SET "CMAKE_GENERATOR=Visual Studio 15 2017 Win64"  

C:\Users\Proxeddu>pushd "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\"  

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>CALL "VC\Auxiliary\Build\vcvars64.bat"  
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

--


Then after completing the caiman installation, I can successfully run the demo_pipeline, but I get errors when running the OnAcid demo which suggests more issues linking to Visual Studio (unable to find a C++ compiler).  

In particular I get these messages/errors when running the OnAcid demo: 


1): 
Using Theano backend.
       48700 [configdefaults.py:            <module>():515] [18804] g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Anaconda3\envs\caiman\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
       48706 [configdefaults.py:            <module>():580] [18804] g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
       48877 [configdefaults.py:default_blas_ldflags():1458] [18804] install mkl with `conda install mkl-service`: No module named 'mkl'
       48877 [blas_headers.py:            <module>():988] [18804] Using NumPy C-API based implementation for BLAS functions.

2): 
C:\Anaconda3\envs\caiman\lib\site-packages\theano\tensor\nnet\conv.py:98: UserWarning: theano.tensor.nnet.conv.conv2d is deprecated. Use theano.tensor.nnet.conv2d instead.
  warnings.warn("theano.tensor.nnet.conv.conv2d is deprecated."
      126308 [opt.py:                warn():1910] [18804] Optimization failure due to: local_abstractconv_check
      126308 [opt.py:                warn():1911] [18804] node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, 32, 23, 23), kshp=(64, 32, 3, 3), filter_dilation=(1, 1), num_groups=1, unshared=False}(InplaceDimShuffle{0,3,1,2}.0, InplaceDimShuffle{3,2,0,1}.0)
      126308 [opt.py:                warn():1912] [18804] TRACEBACK:
      126325 [opt.py:                warn():1913] [18804] Traceback (most recent call last):
  File "C:\Anaconda3\envs\caiman\lib\site-packages\theano\gof\opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "C:\Anaconda3\envs\caiman\lib\site-packages\theano\tensor\nnet\opt.py", line 500, in local_abstractconv_check
    node.op.__class__.__name__)
theano.gof.opt.LocalMetaOptimizerSkipAssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against? On the CPU we do not support float16.

3) 
A long error message tracing lines of code. 

Note that if I can't resolve the error by simply following the error message suggestions by running: 
conda install m2w64-toolchain
conda install mkl-service

--
I would greatly appreciate any advice on getting the installation to work so that OnAcid works properly.

Thanks!

**Comment by pgunn** [comment]
Hi,
I thought we had noted what VC++ components needed installation; if you remember what you needed to add that was not there by default, we can update our docs. I think the latter issue you were hitting came from Theano not being a supported configuration for CaImAn ; we intend for people to use the Tensorflow backend for Keras. If you can do

```
SET KERAS_BACKEND=tensorflow
```

before running CaImAn code, that'll hopefully help (if it leads to different errors, we can help you through those)

**Comment by vathalye** [comment]
Hi Pat, 

Thanks very much for your quick reply; much appreciated!  Running:
SET KERAS_BACKEND=tensorflow
Solved the OnACID errors.  
(I'm not sure why running "activate caiman" sets KERAS_BACKEND to theano...  )

Thanks!

--

For the VC++ components, I believe "activate caiman" triggered searching for an older version of build tools from VS2015 version 14.0, which leads to the error.  (this is likely similar to this issue: https://github.com/flatironinstitute/CaImAn/issues/411).  I happened to resolve this by 1) modifying my build tools installation by installing and then uninstalling VC++ 2015.3 v14.00 toolset for desktop and 2) uninstalling visual studio community (which I happened to have installed).

**Comment by pgunn** [comment]
@vathalye  Ah, that's interesting. One of the harder things for us to control on Windows compared to the other platform is the wider variety of likely systems configurations (I would not be surprised if visual studio community coexisting with the CLI tools was part of the problem there).

As for what's happening with the KERAS_BACKEND env var, unfortunately on Linux and Windows the Keras library is packaged with Theano as its preferred backend (on OSX it defaults to tensorflow I think), and installing keras into an environment makes a keras_activate.sh (or on windows, keras_activate.bat probably) that sets that. If you're feeling adventurous you can poke around in your conda directory under

```
envs\$ENVNAME\etc\conda\activate.d\keras_activate.bat
```

and edit that file to have it default to tensorflow instead. Or the name should at least be fairly close to that.

**Comment by vathalye** [comment]
@pgunn , 
Ah thanks!  yes, I changed the setting in 
envs\$ENVNAME\etc\conda\activate.d\keras_activate.bat, which previously set the backend to theanos.

I also found and deleted "vs2015_compiler_vars.bat" from this directory, as @symonova suggested, and now "activate caiman" does not result in output text related to vs2015.

Thanks!

**Comment by akim5651** [comment]
Hi @pgunn 

I appreciate your help on this issue so far. I have not been able to successfully activate caiman as well as have been having problems with caimanmanager.py. 

Running Windows 10, Python 3.7 thru Anaconda (installed as described in the Readme). Upon getting to 'activate caiman' on the python terminal, the prompt abruptly closes. I have tried entering in, "conda install -n caiman vs2017_win-64", and the prompt still closes without any change. I am fairly new to python, and would appreciate any help. Thank you.

**Comment by pgunn** [comment]
@akim5651 Hi, can you find and delete vs2015_compiler_vars.bat under your conda dir? It may be a few directories deep.

**Comment by akim5651** [comment]
This worked, thank you!

**Comment by Xudangliatiger** [comment]
Gentle and elegant.

**Comment by zcq0730** [comment]
A solution to the problem by following procedures: (supporting VS2019)
1. delete: envs$ENVNAME\etc\conda\activate.d\keras_activate.bat
2. modify vs2017_compiler_vars.bat contents as in the picture indicated.
3.  remember to run following lines in anaconda prompt.
     set MKL_NUM_THREADS=1
     set OPENBLAS_NUM_THREADS=1
     set KERAS_BACKEND=tensorflow
That´s everything you need to do. To emphasize, VS2019 also works.
The rationale behind was that python just needs a C interpreter. 
By doing above, we tell python where to find the C interpreter. That´s all.
Hope it will help you as well. Good luck!

![vs2019](https://user-images.githubusercontent.com/40316783/60833040-b0495e80-a1bd-11e9-88a0-eabdf020de10.JPG)

**Comment by epnev** [comment]
@pgunn ^^^^^
@zcq0730 Thanks!

**Comment by zcq0730** [comment]
> @pgunn ^^^^^
> @zcq0730 Thanks!

Thanks a lot for the very nice work! The solution was largely based on @pgunn ´s comments.
And some hints from this link: https://stackoverflow.com/questions/53524031/how-to-deal-with-error-at-activating-environment

**Comment by RahulKamma0369** [comment]
i too got the same error ,i've cleared it by deleting etc file from anaconda3 folder;

**Comment by Hanbing1999** [comment]
> @Zaikkp Hi, did you get the chance to try any of the above?


> "vs2015_compiler_vars.bat" from this directory



> Thanks for the suggestion. I had the same issue in Windows 10: conda terminal crashed after trying to activate caiman environment.
> As you recommended, I executed:
> `conda install -n caiman vs2017_win-64`
> I also removed the file vs2015_compiler_vars.bat which was causing the terminal to crash. After that I could complete the installation.

But I did not find vs2015_compiler_vars.bat in my directory. I only found vs2017_compiler_vars. Should I delete them?

**Comment by pgunn** [comment]
@Hanbing1999 If you need to, although nowadays we have a binary package for Windows that doesn't have any of these issues, provided you don't need to change the caiman library code.

**Comment by Hanbing1999** [comment]
> @Hanbing1999 If you need to, although nowadays we have a binary package for Windows that doesn't have any of these issues, provided you don't need to change the caiman library code.

Thanks! But now I have another problem that when I run pip install caimanmanager.py in the environment of caiman, it is reported that ERROR: Could not find a version that satisfies the requirement caimanmanager.py (from versions: none)
ERROR: No matching distribution found for caimanmanager.py
What should I do?  (By the way, I installed caiman by typing  pip install -e . as shown in the following codes) 
(caiman1) pip install -e .
Obtaining file:///C:/Users/Hanbing/CaImAn
Installing collected packages: caiman
  Running setup.py develop for caiman
Successfully installed caiman

**Comment by pgunn** [comment]
Hi,
That commandline (pip install caimanmanager.py) doesn't make sense. There are two main ways you can install our software - either tell conda to do it, or download the sources and compile it. Both work.

After installing the package as a library, *then* caimanmanager.py shoujld be in your path, and you should be able to do `caimanmanager.py install`.

The docs should cover this, although I'm happy to help you here too.

**Comment by Hanbing1999** [comment]
Thanks for your response! But after I type `caimanmanager.py install ` in （caiman), it is reported that 'caimanmanager.py' is Not internal or external commands, nor runnable programs or batch files. Should I type 'caimanmanager.py install' in base environment or just C:/? 
Thanks!

**Comment by Hanbing1999** [comment]
```
(caiman1) conda install caimanmanager.py
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - caimanmanager.py

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

But after I download the package by conda, it is reported that they cannove found this package.

**Comment by pgunn** [comment]
Hanbing, that's still not how to install it that way. Do this:

`conda create -n caiman -c conda-forge python=3.7 caiman`
Let me know how that goes.

**Comment by Hanbing1999** [comment]
> Hanbing, that's still not how to install it that way. Do this:
> conda create -n caiman -c conda-forge python=3.7 caiman
> Let me know how that goes.

Should I run this in caiman environemnt?

**Comment by pgunn** [comment]
No - delete your existing environment with `conda env remove -n caiman` first. Then run the command above, which will make for you a new conda environment.

**Comment by Hanbing1999** [comment]
> conda env remove -n caiman

Ok, I actually name the environment as caiman1 (D:\Python_install\envs\caiman1\share\caiman), so I just need to type `conda env remove -n caiman1` and then `conda create -n caiman1 -c conda-forge python=3.7 caiman`

**Comment by pgunn** [comment]
Yes. That should do it.

**Comment by Hanbing1999** [comment]
> Yes. That should do it.
This is what I get: 
1. the package of caiman-1.8.3  was downloaded to 6% 
2. ```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/caiman-1.8.3-py37h3bbf574_0.tar.bz2>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by pgunn** [comment]
Let's continue this on #773 so we don't bother the people who were on this closed ticket.

**Comment by ljubanradisin** [comment]
> @akim5651 Hi, can you find and delete vs2015_compiler_vars.bat under your conda dir? It may be a few directories deep.

It worked in my case, now only difference was that it was vs2017
