### ISSUE TITLE
Code for extract ∆F/F in jupyter notebook.

### ISSUE THREAD

**Issue by bingcao2** [flatironinstitute/CaImAn#420]
Hi,
Since I could only use jupyter to run the code in notebook without spyder, could you tell me how to get  ∆F/F in jupyter? Here is some hints previously, but I still don't know how to write the code. I do appreciate if you could write the code to extract all the ∆F/F and could paste it into excel for further plotting. Many thanks!

Quoted from epnev
> The DF/F traces are included in cnm.estimates.F_dff. If you want to store them separately you can use some numpy command, e.g., np.savez
>

_Originally posted by @bingcao2 in https://github.com/flatironinstitute/CaImAn/issues/409#issuecomment-442183541_

**Comment by agiovann** [comment]
dear @bingcao2,
in demo_pipeline (https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline.ipynb)

there is a cell that computes DF/F
#%% Extract DF/F values
cnm2.estimates.detrend_df_f(quantileMin=8, frames_window=250)

In order to save in excel files I would consider weither to learn using pandas, or use https://xlsxwriter.readthedocs.io/
CaImAn provides the output in matrix form, and the final user can then manipulate the data with customized tools

**Comment by omidm7** [comment]
Hello, I tried to input the line:

#%% Extract DF/F values
cnm2.estimates.detrend_df_f(quantileMin=8, frames_window=250)

Right after plotting contour plots in the demo_pipeline_cnmfE. I changed 'cnm2' to 'cnm' because I did not need to re-run the cnmf. I got the following error line. Can someone help me interpret it?
Thank you.


![image](https://user-images.githubusercontent.com/44180252/50317147-f7b10d00-046e-11e9-9df1-8f46bb5af607.png)

**Comment by agiovann** [comment]
@bingcao2 sorry about the delay. You can access it from 

cnm2.F_dff

Happy holidays!

**Comment by epnev** [comment]
@bingcao2 To correct the comment above: the DF/F values are in `cnm2.estimates.F_dff`
If you want to save them in a separate variable you can simply type `F_dff = cnm2.estimates.F_dff.copy()`
Every row of `F_dff` will correspond to a component and every column to a timestep.
I believe that your issue is addressed and I'm closing it but feel free to re-open if you still have questions.

**Comment by sofiapuvogelvittini** [comment]
dear @bingcao2 , Could you resolved the issue?
I have the same one, this cnm2.estimates.F_dff does not gave me a variable in spyder! It gaves me a NoneType object.
I will really appreciate your help.
Kind regards,
Sofía
