### ISSUE TITLE
Extracting ∆F/F after cnmfE

### ISSUE THREAD

**Issue by omidm7** [flatironinstitute/CaImAn#424]
**(macOS)**,
Python **(3.6)**,
 **(Spyder)**

Hello,
After running my one-photon data through the CNMF-E demo pipeline, I'm trying to extract ∆F/F. I used the following line from the general demo pipeline:
    #%% Extract DF/F values
    cnm.estimates.detrend_df_f(quantileMin=8, frames_window=250)

I get the following error:

![image](https://user-images.githubusercontent.com/44180252/50499983-db7b1600-0a02-11e9-9e83-7497c4849511.png)

Is there another line I'm supposed to use for 1p data?

Omid

**Comment by epnev** [comment]
@omidm7 Extracting DF/F values using the CNMF-E algorithm is not possible with this method. In general we do not recommend extracting DF/F for 1p data (which is what CNMF-E is being used for) because the background contains signal from multiple sources due to the large integration volume. The error you are observing is because the background in 1p data is not being represented in the same way as in 2p data, i.e. with a set of spatial and a set of temporal background components.

**Comment by omidm7** [comment]
@epnev Thanks for the clarification! As a followup, after CNMF-E, does the temporal data in estimates.C already account for estimates.b0? Or should I subtract the baseline values?

**Comment by epnev** [comment]
@omidm7 
- `estimates.b0` refers to the overall background baseline and does not need to be subtracted from `estimates.C`.
- `estimates.C` should be interpreted as an estimate of the fluorescence trace of the corresponding component up to a linear transformation. As such it is in absolute units. We cannot get exact units for `estimates.C` because (among other reasons) the spatiotemporal fluorescence is expressed as the product of the spatial and temporal component. A DF/F transformation can make `estimates.C` unitless but for 1p data the baseline fluorescence of a neuron cannot be distinguished from the strong neuropil activity due to the very large integration volume.

I'm closing the issue but feel free to ask more questions. The CNMF-E paper should also contain more information.
