### ISSUE TITLE
Manual merging of components

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#484]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
macOS / Linux, Python 3.6, Jupyter Notebook

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
CNMF source extraction identifies a number of components that are obviously very similar. Is it possible to somehow merge them 'manually' after the source extraction step? For example, if components 1 and 2 are very similar, is there a way to create one component out of the two (e.g. the average of the spatial footprint) and update the corresponding estimates?

**Comment by epnev** [comment]
@hluetck We already have some old functions that could be used for that. I'll look into creating an `estimates` method that operates around them.

**Comment by epnev** [comment]
@hluetck I added a function on the [dev branch](https://github.com/flatironinstitute/CaImAn/blob/dev/caiman/source_extraction/cnmf/estimates.py#L920) which will manually merge a set of pre-defined components. It's a bit experimental and things can get somewhat complicated if you want to manually merge components after you have run the quality evaluation step. The reason being that there is all the quantities you have to recompute for the new components (and the quantities you have to remove for the components that are being merged) and things can get somewhat complicated if you want to do this efficiently. I'll work on it a bit more in the future to integrate it better but I think the basic functionality should be there already.

**Comment by hluetck** [comment]
Thanks for the quick reply. I will look into it and report back.

**Comment by dominic-Evans** [comment]
Dear @epnev and @hluetck, did you look into this further? 

If I merge 3 components before quality evaluation in the demo_pipeline_cnmfe on my own data, and then run evaluate_components, it throws an error because it seems Yra has not been merged but C has (see below). 

Just wondering if you had similar issues.
Thanks


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-216-3af56f793470> in <module>
     13                            'rval_thr': r_values_min,
     14                            'use_cnn': False})
---> 15 cnm.estimates.evaluate_components(images, cnm.params, dview=dview)
     16 
     17 print(' ***** ')

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py in evaluate_components(self, imgs, params, dview)
    865                                          thresh_cnn_lowest=opts['cnn_lowest'],
    866                                          r_values_lowest=opts['rval_lowest'],
--> 867                                          min_SNR_reject=opts['SNR_lowest'])
    868         self.idx_components = idx_components.astype(int)
    869         self.idx_components_bad = idx_components_bad.astype(int)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/components_evaluation.py in estimate_components_quality_auto(Y, A, C, b, f, YrA, frate, decay_time, gSig, dims, dview, min_SNR, r_values_min, r_values_lowest, Npeaks, use_cnn, thresh_cnn_min, thresh_cnn_lowest, thresh_fitness_delta, min_SNR_reject, gSig_range)
    539         -min_SNR_reject) * N_samples
    540 
--> 541     traces = C + YrA
    542 
    543     _, _, fitness_raw, _, r_values = estimate_components_quality( # type: ignore # mypy cannot reason about return_all

ValueError: operands could not be broadcast together with shapes (40,36600) (42,36600)

**Comment by epnev** [comment]
@dominic-Evans Yes, we need to work a bit more on this function to properly update all the relevant fields after the manual merging. I'll put it on my list.

**Comment by dominic-Evans** [comment]
Great, thank you.

**Comment by epnev** [comment]
@dominic-Evans I added some changes in the branch named `merging`. If you want try it out and let me know if it works.

**Comment by dominic-Evans** [comment]
Thank you! I couldn't get it to work though, either without/with running prior evaluate_components:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-adec4bdd79ed> in <module>
----> 1 cnm.estimates.manual_merge(components=[[7,8]], params=cnm.params)

~/anaconda3/envs/caimanmerging/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py in manual_merge(self, components, params)
   1097             fast_merge = True
   1098             bm, cm, computedA, computedC, gm, \
-> 1099             sm, ss = merge_iteration(Acsc, C_to_norm, Ctmp, fast_merge, 
   1100                                      None, g_idx, indx, params.temporal)
   1101 

ValueError: too many values to unpack (expected 7)

**Comment by epnev** [comment]
@dominic-Evans of course, I made changes in all the other places except the actual function that gave the problems..
Can you try again now?

**Comment by dominic-Evans** [comment]
@epnev Great, that seems to be working fine prior to running evaluate_components. Thanks a lot!

**Comment by epnev** [comment]
Thanks!
