### ISSUE TITLE
Correlation/pnr in patch mode?

### ISSUE THREAD

**Issue by etterguillaume** [flatironinstitute/CaImAn#485]
Hi! I know this issue has been brought up a couple of times so this could be more of an enhancement suggestion. I am processing long 1p data with CNMFE, and while running cnmf.fit() on patches works even with lower specs (16Gb RAM) and in single thread mode (no parallelization), it is still a problem to compute the cn/pnr (crashes due to memory overflow, on any machine mac/windows/linux). While this is not a necessary step, it is still very practical to estimate the number of expected neurons for sanity check (and compare it with estimates.A after performing CNMFE to see if some neurons have been missed in the process). I was wondering if using the same patch processing mode as in cnmf.fit() could allow to compute this without memory overflow? Maybe this is already implemented but I am missing something...
In any case thanks a lot for your support!

**Comment by epnev** [comment]
@etterguillaume This can be done, but you can also compute the correlation pnr on a subset of your data, small enough so that it goes through without any problems. E.g. compute it on the dataset obtained by every fifth frame using `images[::5]`. The result will be largely similar, and it highly unlikely that it will lead you to choose different threshold values.

**Comment by etterguillaume** [comment]
Thank you very much for getting back so promptly Eftychios. Temporal downsampling using images[::5] immediately solved the problem and drastically sped up the process. I will close the issue right away, thanks again!
