### ISSUE TITLE
No module named 'caiman'

### ISSUE THREAD

**Issue by lun11** [flatironinstitute/CaImAn#493]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows 10 (64bit), Anaconda

- **Describe the issue that you are experiencing**

I tried to install CaImAn.  I got to "caimanmanager.py install" and received the error "No module named 'caiman'.

- **Copy error log below**

Traceback (most recent call last):
  File "C:\Users\allenli\caimanmanager.py", line 12, in <module>
    from caiman.paths import caiman_datadir
ModuleNotFoundError: No module named 'caiman'

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
After you perform the install, you need to leave the caiman source directory before running caimanmanager.py

**Comment by lun11** [comment]
Hi,
Thank you for the reply.  I entered cd.. before running caimanmanager.py install.  Is that what you meant?

**Comment by pgunn** [comment]
Hi,
Yes. I assume as you just closed the issue that things are working now?

**Comment by lun11** [comment]
Sorry I accidentally pressed close and comment...I meant to just comment.

**Comment by pgunn** [comment]
If you change to an unrelated directory, do you still get the issue? You did the install with pip? Did you get any errors while doing that?

**Comment by lun11** [comment]
(caiman) C:\Users>caimanmanager.py install
Traceback (most recent call last):
  File "C:\Users\allenli\Anaconda3\envs\caiman\bin\caimanmanager.py", line 12, in <module>
    from caiman.paths import caiman_datadir
ModuleNotFoundError: No module named 'caiman'

Yes, the error shows up even if i change to an unrelated directory.  Yes, I installed through "pip install ." and I did not get any errors.

**Comment by pgunn** [comment]
If you do a `conda list` can you verify that the caiman package is in the list of packages in your environment? Maybe cut'n'paste that line and the surrounding few lines?

**Comment by lun11** [comment]
I just did a conda list.  It is in the list of packages in the caiman environment.

![caiman](https://user-images.githubusercontent.com/41491620/54943978-dd247f00-4f08-11e9-99cd-21c83044b77a.PNG)

**Comment by pgunn** [comment]
I have a few theories as to what might be going on (the windows shell environment can be a bit surprising sometimes).

First, I'd like to see what happens when you type
`echo %PATH%`

Second, when you type `python` I'd like to see the stuff it tells you before you hit the interactive python prompt. (hit control-Z to exit that prompt afterwards)

Finally, if you try launching caimanmanager like this instead, do you get the same result?
`python C:\Users\allenli\Anaconda3\envs\caiman\bin\caimanmanager.py install`

**Comment by lun11** [comment]
Typing `echo %PATH%` shows
C:\Users\allenli\Anaconda3\envs\caiman;C:\Users\allenli\Anaconda3\envs\caiman\Library\mingw-w64\bin;C:\Users\allenli\Anaconda3\envs\caiman\Library\usr\bin;C:\Users\allenli\Anaconda3\envs\caiman\Library\bin;C:\Users\allenli\Anaconda3\envs\caiman\Scripts;C:\Users\allenli\Anaconda3\envs\caiman\bin;C:\Users\allenli\Anaconda3\condabin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MATLAB\R2018a\bin;C:\Users\allenli\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\allenli\Anaconda3;C:\Users\allenli\Anaconda3;C:\Users\allenli\Anaconda3\Library\mingw-w64\bin;C:\Users\allenli\Anaconda3\Library\usr\bin;C:\Users\allenli\Anaconda3\Library\bin;C:\Users\allenli\Anaconda3\Scripts;C:\Users\allenli\AppData\Local\Microsoft\WindowsApps;C:\Users\allenli\AppData\Local\Programs\Microsoft VS Code\bin

Typing `python` shows

**Comment by pgunn** [comment]
Ok. So that last thing worked (and you now should have a caiman_data folder).

My guess is that right now you have Windows configured in a way where the .py extension is associated with some python binary out there that's not the anaconda one, and that it's that python that's being used to execute caimanmanager (rather than the anaconda one). This isn't an issue specific to caiman; you may want to remove that association to make anaconda behave better on your system.

If you don't want to do that, explicitly invoking python scripts with the python command should work for you.

**Comment by lun11** [comment]
Great! Thank you so much for your help.  I will try to remove that association.  Thanks!
