### ISSUE TITLE
None background component in cnmf-e

### ISSUE THREAD

**Issue by davegrays** [flatironinstitute/CaImAn#533]
using python3.6, ubuntu 22

using all the cnmf-e settings specified in the demo_pipeline_cnmfE.ipynb notebook, I am getting a None background component (i.e. `f` in `update_spatial_components`), which produces this error during cnm.refit().

/caiman/caiman/source_extraction/cnmf/cnmf.py in refit(self, images, dview)
    373         estimates.select_components(use_object=True)
    374         cnm.estimates = estimates
--> 375         return cnm.fit(images)
    376 
    377     def fit(self, images, indeces=[slice(None), slice(None)]):

/caiman/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indeces)
    496 
    497             logging.info('update spatial ...')
--> 498             self.update_spatial(Yr, use_init=True)
    499 
    500             logging.info('update temporal ...')

/caiman/caiman/source_extraction/cnmf/cnmf.py in update_spatial(self, Y, use_init, **kwargs)
    886             update_spatial_components(Y, C=self.estimates.C, f=self.estimates.f, A_in=self.estimates.A,
    887                                       b_in=self.estimates.b, dview=self.dview,
--> 888                                       sn=self.estimates.sn, dims=self.dims, **self.params.get_group('spatial'))
    889         self.estimates.removed_components.append(removed_components)
    890         return self

/caiman/caiman/source_extraction/cnmf/spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
    209     # we create a memory map file if not already the case, we send Cf, a
    210     # matrix that include background components
--> 211     C_name, Y_name, folder = creatememmap(Y, np.vstack((C, f)), dview)
    212 
    213     # we create a pixel group array (chunks for the cnmf)for the parrallelization of the process

/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py in vstack(tup)
    281     """
    282     _warn_for_nonsequence(tup)
--> 283     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    284 
    285 

ValueError: all the input array dimensions except for the concatenation axis must match exactly

> /usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py(283)vstack()
    281     """
    282     _warn_for_nonsequence(tup)
--> 283     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    284 
    285

**Comment by epnev** [comment]
@davegrays 

The background model for 1p processing is different compared to 2p, which is basically the main difference between the two analysis pipelines. For 1p instead of `estimates.b` and `estimates.f` the algorithm returns `estimates.W` and `estimates.b0` and has a different way of computing the background model. Take a look at equations (1) and (2) [here](https://elifesciences.org/articles/38173#s4) and for more info look into the original [CNMF-E paper](https://elifesciences.org/articles/28728).

The `refit` function won't work with the CNMF-E algorithm the way the code is structured currently. Using `cnmf-e` will implicitly do additional iterations akin to `refit` on its own.

**Comment by davegrays** [comment]
This is fantastic, thank you @epnev for the references!

**Comment by dominic-Evans** [comment]
@epnev Is there a function for reconstructing the background signal for spatial components from estimates.W and b0? Thanks

**Comment by j-friedrich** [comment]
@dominic-Evans we don't have an explicit function to do that at the moment, but it is de facto done in initialization.py lines 1116-1137 and in online_cnmf.py lines 1340-1350, albeit there for merely one frame.

If you did not downsample the background (ssub_B=1) you can construct it simply using
`est = cnm.estimates`
`B = est.b0[:, None] + est.W.dot(Yr - est.A.dot(est.C) - est.b0[:, None])`

where Yr is the data matrix (pixels x time)
If you downsampled (ssub_B>=2) you need to take care of down- and upsampling, e.g. using

`ds_mat = cm.source_extraction.cnmf.utilities.decimation_matrix(dims, ssub_B)`
`B = ds_mat.dot(Yr) - ds_mat.dot(est.A).dot(est.C) - ds_mat.dot(est.b0)[:,None]`
`B = est.W.dot(B).reshape(((est.dims[0] - 1) // ssub_B + 1, (est.dims[1] - 1) // ssub_B + 1, -1), order='F')`
`B = est.b0[:,None] + np.repeat(np.repeat(B, ssub_B, 0), ssub_B, 1)[:est.dims[0], :est.dims[1]].reshape((-1, B.shape[-1]), order='F')`

**Comment by epnev** [comment]
@j-friedrich I think it would be good to include this as a method for the `estimates` module (for both 2p and 1p data) with the appropriate warning that it has big memory requirements. Do you want to do it?

**Comment by j-friedrich** [comment]
Thought so too, hence I pushed it already to the dev branch.
Will add the warning re memory reqs.

**Comment by dominic-Evans** [comment]
@j-friedrich Great, thank you!

**Comment by FedeClaudi** [comment]
Hi, thanks for implementing this feature, very useful. 

I saw the commit on the dev branch and wanted to try it out, but I get an error at this line within `def compute_background(self, Yr)`:
```
ssub_B = np.round(np.sqrt(Yr.shape[0] / self.W.shape[0])).astype(int)
```


The problem seems to be that `self.W` for me is a dictionary with keys `data`, `shape` and others...
Any idea why this is the case? 
Additional info: 

- I'm using caiman version ''1.8.3''
- I'm loading  apreviously saved CNMF-E model using `load_CNMF`, the model was generated with the same caiman version


P.s.: I've tried replacing `self.W` with `self.W['data']` which works, but then I get an error because `cnm.estimates.dims` is `None` [where `cnm` is the loaded model].

**Comment by j-friedrich** [comment]
Hi @FedeClaudi, check out the recent commit to dev I just pushed.
`cnm.estimates.W` is now properly restored as `csr_matrix` upon loading.

Don't know why `cnm.estimates.dims` is `None`, but you can just set it via `cnm.estimates.dims` = `cnm.dims`. (Assuming you have the dimensions stored as `cnm.dims`)

**Comment by FedeClaudi** [comment]
awesome, thank you @j-friedrich
