### ISSUE TITLE
F_dff-OnAci

### ISSUE THREAD

**Issue by skasavica** [flatironinstitute/CaImAn#556]
Hello,

Thanks for the help with matrix S. I would also like to ask for F_dff, because when I want to plot it its an empty matrix and when I print the type(F_ddf) it says :"NonType". Should not that be the numpy array same size as S and C?

Thank you

BR

Sergej

**Comment by epnev** [comment]
@skasavica You can compute that using
```
cnm.estimates.detrend_df_f()
```
However note that the algorithm will have a hard time estimating the baseline for components that were picked up within the last epoch (because their traces will be zero before they were picked up). As such it is recommended that you use 2 or more epochs for your processing before computing the DF/F traces.
