### ISSUE TITLE
feature request: handling scanbox deadband edges

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/CaImAn#589]
scanbox movies contain deadbands on the edges, which should be ignored for processing. I know I could just crop them and convert to hdf5, but it would be nice if this was supported as part of sbx support. I think the method should take an argument for the number of pixels to ignore from both ends of each line (for me it would always be 62).

@bdudok

**Comment by tvajtay** [comment]
Batch converting to Tiffs and cropping with ImageJ is a work around if it is pressing.

**Comment by epnev** [comment]
@bendichter A partial solution to this already exists. During memory mapping, you can pass a variable called `border_to_0` that will exclude a certain number of pixels from the edges. Then you can continue as before. 

The solution is partial because:
- It is not implemented for motion correction, meaning there is no automated way to exclude boundaries during motion correction which might affect the registration results. 
- `border_to_0` takes an int value meaning it will crop exactly the same number of pixels from all sides, a limitation that might not affect your case but should be addressed.

**Comment by epnev** [comment]
Taking a look at the code again, the memory mapping function also has a variable named [`slices`](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/mmapping.py#L310) that will enable more flexible slicing and take care of the second limitation mentioned above.

**Comment by bendichter** [comment]
Oh perfect, thanks! I'll check out those features.

Ben
