### ISSUE TITLE
3D motion correction fails

### ISSUE THREAD

**Issue by liorgolgher** [flatironinstitute/CaImAn#712]
- **Tell us a bit about your setup**: 
 1. Operating system: Linux 
 
 2. Python version: 3.7.6
 
 3. Working environment: Visual Studio Code, same error reproduced through command line.
 
 4. Which of the demo scripts you're using for your analysis: https://github.com/liorgolgher/CaImAn/blob/master/demos/notebooks/demo_motion_correction.py
 
 5. CaImAn version: 1.8.1
 
 6. CaImAn installation process: conda

- **Describe the issue that you are experiencing**

Greetings,

I'd like to use caiman.motion_correction for 3D motion correction of my 4D datasets (txyz). I have cropped a small dataset (200x200x400x200 voxels corresponding to 200 time frames of 200x200x200 um^3 volumetric 2p imagery acquired at 30 volumes per second) and fed it to a modified version of the motion_correction notebook:
https://github.com/liorgolgher/CaImAn/blob/master/demos/notebooks/demo_motion_correction.py

The dataset is available here:
https://drive.google.com/open?id=1MJaar-hn-nYmWCNAmMAywvA74SmxCW26

I've consistently got the error reported below. Switching the boolean values of shifts_opencv and pw_rigid didn't help.
I'd much appreciate it if you could instruct me how to properly use the 3D motion correction module, even if only based on 4D median values returned by bin_median_3d.

Moreover, I'd be happy to hear if the motion correction module supports zarr datasets.

Many thanks in advance,
Lior
Pablo Blinder Lab

- **Copy error log below**
Traceback (most recent call last):
  File "test_moco.py", line 84, in <module>
    mc.motion_correct(save_movie=True)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 254, in motion_correct
    self.motion_correct_rigid(template=template, save_movie=save_movie)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 305, in motion_correct_rigid
    indices=self.indices)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 2672, in motion_correct_batch_rigid
    m = m[:, indices[0], indices[1], indices[2]]
IndexError: tuple index out of range

**Comment by epnev** [comment]
@liorgolgher The motion correction object has another field named `indices` which defaults to `(slice(None), slice(None))`. Try changing that to `(slice(None), slice(None), slice(None))` since your dataset is 3D. The `is3D` flag should have taken care of that but apparently it doesn't. @j-friedrich can you fix that through the `params` consistency method?

Regarding zarr, I've never tried them so I guess the code won't work out of the box. However, adding new formats is easy. All you need is to make sure that you can access portions of the dataset without loading the entire file to memory. After that you need to modify only a couple of methods to include support for a new data format. If you're interested we can direct you to try it out and potentially make a PR.

**Comment by j-friedrich** [comment]
fixed in dev; Currently raising a ValueError if 'max_shifts', 'strides', 'overlaps' aren't tuples of length 3 for 3D data. Or do we have good default values for 3D as well?

**Comment by liorgolgher** [comment]
Thank you both for looking into this matter. The 3D motion correction worked with 
indices = (slice(None), slice(None), slice(None)) 
However:
1. The input 4D dataset was uint8. The motion-corrected 4D dataset was float32 with nearly 50% of its voxels bearing negative values. 1.1% of the motion-corrected voxels were smaller than -0.01 and the minimal voxel value was -1.43, rather than the expected 0. 
2. napari failed to display the motion-corrected 4D dataset, or even a small 57Mb 4D portion off of it which I've biased to become strictly positive.
3. Setting indices to any non-trivial value, be it by stepping (slice(0,None,2), slice(0,None,2), slice(0,None,2)) or by cropping (slice(50,150,1), slice(50,150,1), slice(0,100,1)), resulted in the following error transcript:

Traceback (most recent call last):
  File "/data/Lior/code/test_moco.py", line 94, in <module>
    mc.motion_correct(save_movie=True)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 254, in motion_correct
    self.motion_correct_rigid(template=template, save_movie=save_movie)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 305, in motion_correct_rigid
    indices=self.indices)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 2720, in motion_correct_batch_rigid
    indices=indices)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/site-packages/caiman/motion_correction.py", line 3035, in motion_correction_piecewise
    res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
  File "/export/home/pblab/.conda/envs/caizarr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Error: images must really be same size for register_translation_3d


zarr is [fully multi-threaded](https://clouds.eos.ubc.ca/~phil/courses/parallel_python/03_dask_and_zarr.html) so its integration should be pretty straightforward. Its disadvantages are that [write permissions are currently required to read zarr datasets](https://github.com/zarr-developers/zarr-python/issues/269), and that ImageJ can't open zarr yet. Please tell me which methods should be modified and I'll see if I can handle it.

**Comment by epnev** [comment]
@liorgolgher Check https://github.com/flatironinstitute/CaImAn/pull/677/files that introduces a new file format (although the situation there is simpler since the new format can be treated as a tiff file). But it shows what you need to modify (the modification in `timeseries.py` is for saving into the new format, so in that sense it's optional). But I would advise to first try it out locally and if you think it can be beneficial let us know. We are wary of adding additional dependencies to caiman, since it can complicate maintenance.

Regarding the slicing error, I think there is a problem with the file getting sliced more than once, so only slices of the form `(slice(0,X,1), slice(0,Y,1), slice(0,Z,1))` that leave the file invariant after a second slicing would work (this feature is newish and not tested in detail). I don't have time to look into this but maybe @j-friedrich can do it. (Also @j-friedrich you can replicate values for `max_shifts` etc in the 3D case for the z-axis, since the z-resolution can be very variable we cannot really have good prior knowledge in terms of pixels. An alternative would be to uses the parameter `data.dxy` where you can set spatial resolution and have everything else computed through that although it's not implemented yet inside the options)

Regarding `napari` I've never used it, so I cannot comment on it. The motion corrected file is always saved in float32 format so it can be used for algebraic calculations in downstream processing. About the negative values, what happens is that the original file is shifted to have mostly (but not fully non-negative value) but the corrected file can still have a significant number of negative values due to interpolation effects when applying the shifts.

**Comment by j-friedrich** [comment]
I fixed the slicing issue for volumetric data in master and dev. Both stepping and cropping work now.
I also replicated values for the z-axis.

**Comment by j-friedrich** [comment]
actually closing this issue, because 
1. negative values aren't unexpected
2. the limitations of napari are outside of our scope
3. slicing works in the most recent commit
