### ISSUE TITLE
Question about getting the f0 trace of a cell

### ISSUE THREAD

**Issue by Ruyi-Yang** [flatironinstitute/CaImAn#731]
I wonder to know how to get the trace of f0 of a cell, I can get its F and DF/F trace now.
Thank you!

**Comment by epnev** [comment]
@Ruyi-Yang Unfortunately, this quantity is not stored by the algorithm but there is a work-around to derive it without modifying the code: 

If you look at the [source code](https://github.com/flatironinstitute/CaImAn/blob/a1e325928e3cbe49614cdcb601896a4ee74d0bff/caiman/source_extraction/cnmf/utilities.py#L296) there is a distinction between the baseline fluorescence for the trace of each component (denoted as `Fd`) and the baseline fluorescence due to the background denoted as `Df`. What you can do is the following (see [this part of the code](https://github.com/flatironinstitute/CaImAn/blob/a1e325928e3cbe49614cdcb601896a4ee74d0bff/caiman/source_extraction/cnmf/utilities.py#L414-L417) for reference) :
- Run the `detrend_df_f` with setting the `detrend_only` flag to `True`. This will give `F_df = F - Fd` and you can derive `Fd = F - F_df`. 
- Then run it again with setting the flag `detrend_only = False` (which is the default) and use the newly derived `F_df` and the previously derived `Fd` to solve for `Df = (F - Fd)/ F_df + - Fd`. 
It's a bit weird but it should work.

**Comment by Ruyi-Yang** [comment]
Thanks for your reply. I want to know what the default values of window and stride are when estimating f0. I did n’t make any adjustments in data analysis. 
And for example, if the stride length is 50, how is the f0 of the first 49 frames determined?

**Comment by epnev** [comment]
The default value is `frames_window=500` as shown in the source code.  Baseline values are computed by computing a percentile in non-overlaping segments with that length. These values are then upsampled back at the original length to give an `f0` value of the same length. If the traces are shorter than `frames_window` then the baseline value is just the percentile over the whole trace.

**Comment by Ruyi-Yang** [comment]
Sorry to bother you, I want to ask why the default value of frame_window should be set to 500.
Thank you.

**Comment by epnev** [comment]
It is a default value based on empirical observations. You can change it to
whatever you think is best.
