### ISSUE TITLE
Question about estimates.C being negative for 1p data

### ISSUE THREAD

**Issue by danachang** [flatironinstitute/CaImAn#738]
Hi,

I got a miniscopic 1P data analyzed through CalmAn package. I am curious why a denoised `C` where some of its baseline is negative. I thought CNMFe and most algorithms described in the paper (https://elifesciences.org/articles/38173) use non-negative constraints on `C.` I am thus curious why some of the `estimates.C` start at negative baselines?  My own guess is that the original OASIS algorithm did not have non-negative constraint on `C.` Is this the main reason?  

Followed on this, I have questions on how to interpret `estimates.C` with negative baselines.  In CNMFe algorithm, they suggested that `C` is viewed as a scaled version of `dF/F` for 1P data, and people should use it to replace `dF/F.` However, if the baseline is not at 0, I'm not sure how to interpret these traces. Should I just shift the `estimates.C` such that their baseline is at 0?  

Thanks!

**Comment by j-friedrich** [comment]
You can enforce the non-negativity constraint on `C` by setting `bas_nonneg=True` when creating the `cnmf.params.CNMFParams` object. 

Yea, estimating F0 is not well defined for 1p data cause the baseline fluorescence is not just due to the fluorescence of the considered cell but other sources.  You can get the shifted traces as `estimates.C-estimates.bl`.

**Comment by danachang** [comment]
Thank you very much!
