### ISSUE TITLE
Error exporting to nwb

### ISSUE THREAD

**Issue by maxrioux100** [flatironinstitute/CaImAn#759]
- **Tell us a bit about your setup**: 
 1. Operating system (Windows): 
 
 2. Python version: (3.6.10)
 
 3. Working environment: (Jupyter Notebook)
 
4. Demo script: Custom but mostly similar to cnmf-e demo.

 5. CaImAn version*: 1.8.3
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): Conda

Hello, 
First of all, I want to say thank you. CaImAn performed way better for my data than I would have hoped for.
I will start by saying what is working. In fact basically anything up to that point, motion, correction, correlation image, cnmf-e alogrithm (find and circle the components, find the time series). I can even display the final components correctly with cnm.estimates.nb_view_components.

But I have 2 errors (I think both of them are related)
The first one is when Im trying to open my hdf5 output from caiman_gui.
![Capture](https://user-images.githubusercontent.com/40430512/82902355-5795c800-9f2d-11ea-8f0f-55ee70763a78.PNG)

The second and most important one is when im trying to export to the file format nwb.
![Capture2](https://user-images.githubusercontent.com/40430512/82902474-7eec9500-9f2d-11ea-8606-ccac15d4deec.PNG)

From what I understand, its because it has no background components. 
I tried to run estimates.detrend_df_f as a test and got that output.
![Capture3](https://user-images.githubusercontent.com/40430512/82902653-c96e1180-9f2d-11ea-8d24-4d51f7cf53cd.PNG)
Im not exactly sure what this does since im new to this but from what I read this is not supposed to be used for 1p data. But since it can help solving the main issue, I add it there.

Help is greatly appreciated,
have a nice days,                                                                                                                      Max

**Comment by maxrioux100** [comment]
If I try to set the param nb to 1 and nb_patch to 1 (They were originally both equal to zero
![Capture4](https://user-images.githubusercontent.com/40430512/82915302-8cf6e180-9f3e-11ea-9042-ea96e0495b54.PNG)
), I get this error

**Comment by epnev** [comment]
@maxrioux100 Yes, the reason the save fails is because there is no `b` and `f` for the CNMF-E 1p processing pipeline. I guess a quick hack to fix this would be to manually set a component manually:
```
self.estimates.b = np.zeros((self.estimates.A.shape[0], 1))
self.estimates.f = np.zeros((1, self.estimates.C.shape[1]))
```
and then save. However, I don't think the CNMF-E background specific components get saved here in case you're interested in them. @bendichter might know better.

Same for the GUI, I don't think it will work for CNMF-E output, or if it does it won't have any background information.

**Comment by maxrioux100** [comment]
Thanks, I will try that tomorrow morning. I don't care about the background components so this will be perfect.

**Comment by j-friedrich** [comment]
@maxrioux100 For adapting the GUI to somewhat work with unsupported CNMF-E output see also issue #741

**Comment by maxrioux100** [comment]
@j-friedrich I will check that after the main issue is solved :)
@epnev Now it output a very strange error. Do you have any idea why ?
![Capture5](https://user-images.githubusercontent.com/40430512/83146583-885c3580-a0c4-11ea-9a65-c3577c3fdfa8.PNG)

**Comment by epnev** [comment]
@maxrioux100 Unfortunately the NWB code was externally contributed by the NWB developers and personally I cannot offer a lot of support here. You can try going over to their repo and mention this issue.

**Comment by bendichter** [comment]
I can take a look later today

**Comment by bendichter** [comment]
@maxrioux100 it's hard for me to resolve this error entirely without being able to reproduce it, but let me explain what is going on here from the NWB side and maybe we can converge on something.

Each ROI image mask is in a row of the `PlaneSegmentation` table. The `RoiResponseSeries` is linked to the `PlaneSegmentation` table via a `DynamicTableRegion`, which match specific rows of the `PlaneSegmentation` table to columns of the `RoiResponseSeries`. This error is due to `ps.create_roi_table_region(..., region=list(range(n_rois)))`. For some reason `n_rois` is greater than the length of the `PlaneSegmentation` table called `ps`. The error suggests that the table has only a single row. I'm guessing this has something to do with assumptions we made during the development of this feature that don't hold up in your case. Do you know what might be causing this discrepancy?

I can take a look at fixing this myself if you can guide me through reproducing the error.

**Comment by maxrioux100** [comment]
@bendichter Hello ben, I shared the file you need to reproduce the error via google_drive to the gmail in your github profile 10 days ago, did you get it ? 
I tried to understand your message and find whats wrong but I can't figure it out.

Have a nice day, Max

**Comment by bendichter** [comment]
@maxrioux100 Thanks for letting me know. There's a lot going on in that notebook. Are you able to save the data in another format, load the data, try to save it in NWB, and get the same error? If so, an easier way to solve this might be for you to give me the data saved in another format so I can more easily reproduce the error instead of downloading a large amount of data and going through your entire processing pipeline.

**Comment by maxrioux100** [comment]
I try this later today and send you the .hd5f if thats the case !

**Comment by maxrioux100** [comment]
I can't find how to load an .hd5f. I tried to look at the page https://caiman.readthedocs.io/en/master/core_functions.html#estimates or searching with keyword like load but I only find how to load a movie or a memmap. 
I opened the .hdf5 with hdfview and everithing seem alright 
![hdf_view](https://user-images.githubusercontent.com/40430512/84065695-c560db80-a992-11ea-9d3c-543fac5b7b69.PNG)
If you can redirect me to the correct function, I will be happy to execute it to see if it generate an error !

**Comment by pgunn** [comment]
@maxrioux100 If you specify hdf5 files as if they were avi or other supported input formats, it should "just work". I think one of the demos load hdf5 (hoping I'm not misremembering).

**Comment by maxrioux100** [comment]
@pgunn I tried cm.base.movies.load(fname) and cm.base.movies.load(fname, var_name_hdf5='estimates') but they both gave me an error about mov. The hdf5 doesnt have the movie in it, just the results. (estimates and params)

**Comment by pgunn** [comment]
Oh, my bad. I know the hdf5-has-the-movies part works.

@j-friedrich Do you know how this part works?

**Comment by epnev** [comment]
@maxrioux100 As I replied in the chatroom the [load_CNMF](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.source_extraction.cnmf.cnmf.load_CNMF) can be used for that.

**Comment by maxrioux100** [comment]
@epnev Thanks it work ! But I won't close the ticket since its not the issue, only a way to reproduce it.


Here is the hdf5 to reproduce the error.
https://drive.google.com/drive/folders/1kp5qDRU5KGF50U1eKH61GaUMq6nNEtJy?usp=sharing

**Comment by bendichter** [comment]
@maxrioux100 

phew! I think I fixed it. There are a few features that we expected for NWB that you don't have, including: `estimates.cnn_preds`, `self.idx_components`, and `self.Cn`. We had assumed that these were present, but it's no problem to omit them if they are missing. I have submitted a PR with the necessary changes.

**Comment by maxrioux100** [comment]
Perfect! I thrust your word that this is working and close the ticket.

Thank you .

**Comment by maxrioux100** [comment]
Hello,
I noticed that the function doesn't seem to save the "accepted" state of the rois.
![Content](https://user-images.githubusercontent.com/40430512/86619482-a4d37380-bf88-11ea-990d-a93eb45b0838.PNG)
The accepted column should all be True since I used 

` cnm.estimates.select_components(use_object=True)`

This doesn't affect me at all but I think you should know.

**Comment by sneezeman** [comment]
In the Caiman version 1.8.8 I get an error trying to use estimates.save_NWB because of the two lines in 
~/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/estimates.py

Lines 1639 and 1652:

```
1639            if self.cnn_preds:
1640                ps.add_column('cnn', 'description of CNN')

1652                if self.cnn_preds:
1653                    add_roi_kwargs.update(cnn=self.cnn_preds[i])
```

In both cases self.cnn_preds is an array, and if returns a ValueError. Replacing self.cnn_preds with any(self.cnn_preds) seems to help. 
It also seems like the next line (1641) is potentially problematic too due to the same potential error, but in my case idx_components is None, so it does work.
