### ISSUE TITLE
Issue creating memmap file after motion correction on cluster

### ISSUE THREAD

**Issue by schoki0710** [flatironinstitute/CaImAn#772]
- **Tell us a bit about your setup:**

 1. Operating system (Linux/macOS/Windows): CentOS Linux 7 on cluster
 
 2. Python version (3.x): 3.6.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Command line
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_cnmfE.py
 
 5. CaImAn version: 1.8.3
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
`conda install caiman -c conda-forge`
- **Describe the issue that you are experiencing**

I am processing a quite large tiff file (~10GB) using multiprocessing on a high-performance cluster, but the process systematically hangs for a long time during motion correction without any error. We have checked with the cluster administrators that the compute node lost control of the workspace where store the tiff file during/after the creation of the F-order memmap file. They suggest writing the intermediate memmap file to the node-local disk. How can I specify in caiman pipeline to write out memmap file in a different directory than the one the original data is located?  

- **If you're not reporting an error, type your message below**

It seems that the issue comes from parallel writing to the same memmap. I have export environment variable to 1 as indicated but the issue still exists. I even tried setting start method to 'spawn' or changing to ipyparallel without success. I didn't understand line 3035 in motion_correction.py:
`res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)`
Would you mind explaining the choice of `map_async()` and why `get(4294967)`? Should we need to `dview.close()` and `dview.join()` after `dview.map_async()`? Thank you for your help!

**Comment by pgunn** [comment]
Hi,
I think if you start your script where you want the tempfile to be, and use an absolute path for file ingest, it should do what you want. Give that a try?

**Comment by schoki0710** [comment]
Apologies for the late responses (got other tasks). On cluster, the node-local disk is accessible only after the job is running so I prefer keep the script at user's home. We adapted the `motion_correction` and `mmapping` codes in scratch to be able to write out in a specified directory and is working for our data on cluster and is faster! Another comments/questions:
- When transpose F-order memmap to C-order, it seems to read a block of columns from F-memmap and write to (physically) segments of C-memmap. Instead, read segments of F-memmap and write to a block of C-memmap (just take rows instead of columns) may be faster if we deal with very large data on HDD.
-  It seems the number of chunks is fixed in both `motion_correction` and `mmapping`. Maybe it is useful to have adapted split size based on the size of data. We have single recording >50 GB so I need to set different split number to avoid using too much RAM. On the contrary, we also have potential RAM issue in CNMF-E that I have no clear ideal (any suggestion about this will be very helpful). Thanks.

**Comment by schoki0710** [comment]
Dear caiman developers,
I remark another thing on the GUI inspection, by default it takes the C-memmap to display movie? I know C-memmap is required to run CNMF but a single big F-memmap is more efficient to play frame images. When working on big file of several tens of GB the difference becomes clear. These are just my thoughts and the codes are working, so feel free to close this issue.

**Comment by j-friedrich** [comment]
Yes, the GUI takes the C-memmap by default, which is not the fastest but the easiest and it is usually present, i.e. saved. We can change that, so that always a FileDialog pops up that is highly suggestive of the C-memmap, but the informed user can select e.g. the F-memmap created during motion correction, if that has been saved.

For motion correction the number of chunks is controlled by the parameter `num_frames_split`. The number is `ceil(T/num_frames_split)`.
For mmapping it is controlled by the argument `n_chunks` in `save_memmap` and `save_memmap_join`.

@agiovann knows more than I regarding the point "transpose F-order memmap to C-order".

CNMF-E is somewhat notorious for high RAM demands. You can either process less patches in parallel by reducing `n_processes`, thus trading lower RAM for longer processing time, c.f. [Fig 8d in the CaImAn paper](https://iiif.elifesciences.org/lax:38173%2Felife-38173-fig8-v1.tif/full/617,/0/default.webp), or use one of our new online methods, [OnACID-E](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_online_cnmfE.ipynb) or [Ring-CNN](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_Ring_CNN.ipynb).

**Comment by agiovann** [comment]
@schoki0710 thank you. Would your transposing strategy work well with parallelization? This is my doubt. We tried several options at the time, and what we came up turned out to be the fastest. It is definitively not a bottleneck right now. At least not for us. How big of a file are talking about?

**Comment by j-friedrich** [comment]
Closing, because @schoki0710 has found a solution.
