### ISSUE TITLE
Documentation of the parameter "nb"

### ISSUE THREAD

**Issue by ajkswamy** [flatironinstitute/CaImAn#776]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
**Cross-platform** 
 2. Python version (3.x): 
 **3.7**
 3. Working environment (Python IDE/Jupyter Notebook/other):
 **Shell/conda**
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 **1.8.4**
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
**conda install -c conda-forge caiman**
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
- **Copy error log below**

- **If you're not reporting an error, type your message below**

Great framework! I have just started to explore component segmentation with CNMF on 1p data.

On [this](https://caiman.readthedocs.io/en/master/Getting_Started.html#parameters) page of the documentation, the parameter for setting the number of background components is said to be "nb". However, from the code [here](https://github.com/flatironinstitute/CaImAn/blob/1a8a2f080135b0b683e23a8f9fe2ed6e6c97c8ef/caiman/source_extraction/cnmf/params.py#L17) and [here](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline.ipynb), I see that it should be specified as "gnb" when using the class "CNMFParams". Additionally, the doc string of this class calls it "nb" [here](https://github.com/flatironinstitute/CaImAn/blob/1a8a2f080135b0b683e23a8f9fe2ed6e6c97c8ef/caiman/source_extraction/cnmf/params.py#L208).

Additionally, the [documentation of this parameter](https://caiman.readthedocs.io/en/master/Getting_Started.html#parameters) says "Defaults to nb = 2", while the init method of the class "CNMFParams" has a default of "gnb=1" and doc string says "nb: int, default: 1" [here](https://github.com/flatironinstitute/CaImAn/blob/1a8a2f080135b0b683e23a8f9fe2ed6e6c97c8ef/caiman/source_extraction/cnmf/params.py#L208).

Am I missing something or should it be "gnb" everywhere with a default of 1?

**Comment by pgunn** [comment]
This appears to be an inconsistency in our docs/defaults (the value, not the name) - we should look over them and make it consistent.

@j-friedrich  The new name was presumably introduced during the CNMFParams refactor over the summer hackathon; if we had to pick a value to be the default, would you suggest 2 or 1?

**Comment by ajkswamy** [comment]
> This appears to be an inconsistency in our docs/defaults (the value, not the name) - we should look over them and make it consistent.

Thanks for the clarification!

**Comment by epnev** [comment]
@ajkswamy This is our own inconsistency and apologies because it is confusing. If you look into the entries of the `CNMFParams` dictionary you'll see there is no parameter called `gnb`.  There is only `nb` which corresponds to the number of background components at a global level, and `nb_patch` which corresponds to the number of (local) background components for each patch. 

As you observed however, when you [define the object](https://github.com/flatironinstitute/CaImAn/blob/1a8a2f080135b0b683e23a8f9fe2ed6e6c97c8ef/caiman/source_extraction/cnmf/params.py#L17) you can pass the argument `CNMFParams(nb=X)` in which case the object will set `gnb=nb` in the dictionary (see e.g. [here](https://github.com/flatironinstitute/CaImAn/blob/1a8a2f080135b0b683e23a8f9fe2ed6e6c97c8ef/caiman/source_extraction/cnmf/params.py#L699)). This was the old way we used to define the object which is now considered deprecated. Now we use the dictionary as you show in your [second example](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline.ipynb) where if you observe, what is being passed in the dictionary is `nb`. We just left the name of the local variable as `gnb` probably for back-compatibility issues and never changed it. 

Hope that makes sense.

**Comment by ajkswamy** [comment]
@epnev This makes it clearer, thank you!

**Comment by epnev** [comment]
@ajkswamy As default I'd say use `nb=2` but you may want to experiment a little bit.
