### ISSUE TITLE
negative value in estimates.C

### ISSUE THREAD

**Issue by SabriQ** [flatironinstitute/CaImAn#783]
You can enforce the non-negativity constraint on `C` by setting `bas_nonneg=True` when creating the `cnmf.params.CNMFParams` object. 

Yea, estimating F0 is not well defined for 1p data cause the baseline fluorescence is not just due to the fluorescence of the considered cell but other sources.  You can get the shifted traces as `estimates.C-estimates.bl`.

_Originally posted by @j-friedrich in https://github.com/flatironinstitute/CaImAn/issues/738#issuecomment-613759288_

I'am curious about what the exact process by  setting `bas_nonneg=True` , is it the same to `estimates.C-estimates.bl`? by the way, what is the definition of estimates.bl. I can not find in the documents.

**Comment by epnev** [comment]
@SabriQ It is not. During the deconvolution process an optimization problem is solved where the baseline is one of the variables (together with the neural activity signal `S`). Setting it to be non-negative poses an additional constraint to the problem and might change the overall solution. In other words, there are no guarantees that the deconvolved signal will be the same up to a baseline shift. In fact with negative baseline, the optimization might find more deconvolved activity since the latter will sit on top of a lower baseline value.
