### ISSUE TITLE
Seeming failure on long videos?

### ISSUE THREAD

**Issue by ckemere** [flatironinstitute/CaImAn#857]
Hi,

I'm running on Ubuntu 20.04 with the most recent git version of Caiman. I'm running a script taken from the CNFM-E demo, which starts after the motion compensation to just run cnm.fit(). I'm running on an AMD-Epyc workstation with 24 threads enabled and 300 GB of memory. The video that I'm trying to process has ~300K frames, which have been pre-downsampled by a factor of 2 (to ~640x480), and then I'm using the standard settings from the example. 

I'm finding that things seem to stall in a way that I can't explain. I see that the threads that have been spawned are still there, and have maximized memory but they're not consuming any processor (after 12 hours). Is there a way to force the multiprocessor threads to garbage collect each time they process a patch?

thanks,
Caleb

**Comment by pgunn** [comment]
Hi,
A few things to look at:

1) Use htop to look at your memory usage to see how close you are to hitting limits
2) Try changing the number of threads you're using; you may have more luck with more threads
3) Is it all threads that are blocked, most, or all-but-one?

I suspect this has nothing to do with memory garbage collection.

**Comment by ckemere** [comment]
htop claims I'm using 54/315 GB memory total. Oddly, I see many more than 24 threads associated with my job. Am I missing something there? Should I just see the 24 I specified?

This had already happened when I used 64 threads (2x the number of cores, which is the default). Are you suggesting trying more threads than processors?

All threads are in the "S" state.

**Comment by pgunn** [comment]
I'd try fewer threads to see if it is better-behaved. I wonder/worry there may be race conditions in some of the python multithreading code.

**Comment by j-friedrich** [comment]
Some final comments before closing:

Make sure to set the environment variables
```
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
```

Using a lower number of processes reduces the required memory on the expense of longer processing time because less patches are processed in parallel, see Figure 8d in the [CaImAn paper](https://elifesciences.org/articles/38173/figures#content).

Our newer online methods are especially appropriate for long videos and could be used. They have only minimal memory requirements, see the [online demo](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_online_cnmfE.ipynb) as well as the [realtime demo](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_realtime_cnmfE.ipynb).
