### ISSUE TITLE
RuntimeError: cannot merge if there are empty patches.

### ISSUE THREAD

**Issue by Mtkostecki** [flatironinstitute/CaImAn#900]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable): https://colab.research.google.com/drive/1vkp-uPV8tKavmX12bcN2L-jYH8_MgmHL?usp=sharing#scrollTo=xz-fEjUMCAaF
 
 5. CaImAn version*:  1.9.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e .`/conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Hi, I have an error when I try to run CNMF - and I am not sure what is the reason; when I use caiman Matlab, I also get error at the same point (Expected input number 1, A, to be nonempty.)

- **Copy error log below**

RuntimeError: cannot merge if there are empty patches.

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
@Mtkostecki Can you please comment out line 144 in caiman/source_extraction/cnmf/map_reduce.py, which raises this Error and report back. (Or use the dev branch, which doesn't have this line)
This line is due to pull request #548. However, if I remember correctly, the code should be robust (now, maybe not when the PR was issued) to patches that don't include any components.

**Comment by Mtkostecki** [comment]
Worked!
