### ISSUE TITLE
estimates.F_dff baseline negative

### ISSUE THREAD

**Issue by jorareshuaiwang** [flatironinstitute/CaImAn#921]
- **If you're not reporting an error, type your message below**

Hi, I extracted my trace (estimate.C) very nicely. However, the dff traces (estimate.F_dff) showed negative baseline for some traces, which is obviously wrong. How to correct this negative value? Or is there a way I could calculate dff from estimate.C?
<img width="918" alt="C" src="https://user-images.githubusercontent.com/29548369/135581358-3d3fc3c0-f6ba-4326-aa0d-a1f263c07d1a.png">

[](url)
<img width="898" alt="F_dff" src="https://user-images.githubusercontent.com/29548369/135581369-9470486e-57e1-4dc3-b913-b5a29a9cb725.png">

Thanks!
Shuai

**Comment by EricThomson** [comment]
@j-friedrich I know this is a very old issue, but I am not sure of the answer off the top of my head I'm assuming this must be CNMF not CNMFE. There are lots of issues about negative values in C, but not that I've seen about DFF:
#738
#783 
#834

**Comment by EricThomson** [comment]
Thinking about this more:  this is a fairly complex topic. The point of traditional dfof is that it is deflections from some baseline measure, so will include negative values, so I wouldn't say it is obviously wrong to have negative values.  Imposing non-negativity constraints would defeat the purpose of such traditional dfof measures.

If you just want to normalize relative to intrinsic noise, and get normalized unitless deviations from the min val using such a measure, that is possible too, so if that is what you are after then we could discuss how to do that. This is what I do with 1p data.

**Comment by ggmirandac** [comment]
Hi @EricThomson 

I am working on the same stuff here. Like I am calculating the F_dff value of the messurements and I get negative values, which biologically don't make a lot of sense since we want to calculate the AUC of the F_dff. After running the 1p data, with the CNMF-E algorithm, we get the following traces:
<img width="579" alt="Screenshot 2023-09-29 at 18 49 16" src="https://github.com/flatironinstitute/CaImAn/assets/63483031/aa3746a0-0a55-425b-a59c-59cefb96f471">

And as you can see, there are negative points, which for this analysis would mean that there is like "negative amounts of Calcium". Could you help me to generate this analysis? It seems like you have figure how to go through these problems.

**Comment by EricThomson** [comment]
As I mentioned above, I'd be careful of interpretation here. dfof isn't measuring calcium, that would be C. dfof is measuring deviation from baseline and is commonly negative. To set the baseline nonnegative, `nonneg_bas` should yield that for `C`, but there are no guarantees for dfof -- it is common for changes relative to baseline to be negative.

I do want to better explain dfof and offer more options in the future, as I don't think we explain it very well in the docs.
