### ISSUE TITLE
Rules of process generation by caiman?

### ISSUE THREAD

**Issue by lanluo9** [flatironinstitute/CaImAn#954]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook via VSCode
 
 4. Which of the demo scripts you're using for your analysis (if applicable): /
 
 5. CaImAn version*: 1.9.4
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): `pip install -e .`

- **If you're not reporting an error, type your message below**

Hi! I'm trying to make caiman processes "nice" by setting python processes of my user account to a lower priority, so that caiman doesn't freeze other users on the same computer. I'd like to confirm at which point new python processes get generated by caiman:

In demo_pipeline.ipynb, does `c, dview, n_processes = cm.cluster.setup_cluster(backend='local', n_processes=None, single_thread=False)` mean that new python processes are generated in this line to accommodate dview workers, and that caiman doesn't generate python processes elsewhere?

Thank you for your help!

**Comment by pgunn** [comment]
Hello,
These are handled by whatever parallelisation backend you're using rather than in caiman code itself, which will nearly always in practice be either ipyparallel or multiprocessing. The easiest thing to tune there is the number of processes either use (we provide knobs for doing so).

It's more work to go after the niceness level (and unclear if it will really make a difference); there's an approach that might work in theory for multiprocessing (but it's involved, and integrating it into caiman may be nontrivial). I'd need to dig further on how to do it with ipyparallel.

In general we haven't thought a lot about use on multiuser systems; Caiman uses enough memory that that's often the point of contention rather than CPU usage. 

Happy to talk about this further with you.

**Comment by lanluo9** [comment]
Thank you for your reply! For my set up, the parallelisation backend is "multiprocessing". I could change the value assigned to `n_processes` to see if it helps free up CPU usage for other users. For now I'm using a very crude method shown [here](https://github.com/lanluo9/inter/blob/master/code/py_playground/set_caiman_nice.ipynb), which requires caiman to be run on a separate user account. 

I'd be glad to learn about the approach that might work for multiprocessing, since it would be nice (haha) to only target caiman processes instead of targeting all python processes under one user.

**Comment by pgunn** [comment]
I found this, which looks a little bit involved:
https://stackoverflow.com/questions/59579859/set-niceness-of-each-process-in-a-multiprocessing-pool

I'd explore the n_processes route first though because it's far less invasive and far less fuss.

**Comment by lanluo9** [comment]
Thank you! I'll go try these out :)

**Comment by pgunn** [comment]
Some of the notebooks create the pool for one purpose, use it, shut it down, and create it again afterwards; if you explore this way of controlling pool niceness, remember that you may need to do it more than once.
